### ISSUE TITLE
I2c broken on 2025.8.x - components marked failed after a power cycle after successful OTA update

### ISSUE THREAD

**Issue by bharvey88** [OttoWinter/esphomeyaml#10550]
### The problem

This issue is present on the Apollo AIR-1 devices using a esp32 c3 mini mcu.

[brandon-air-1_logs.txt](https://github.com/user-attachments/files/22124081/brandon-air-1_logs.txt)

Steps to reproduce: flash new version of 2025.8.x esphome, flash succeeds, entities available, power cycle (not reboot, only power cycle), and now the i2c devices all are marked failed on boot.

Additional info: it actually seems to sometimes boot successfully and not mark the SEN55 component failed and other times marks it failed. - logs attached.

### Which version of ESPHome has the issue?

2025.8.2

### What type of installation are you using?

Home Assistant Add-on

### What platform are you using?

ESP32

### Component causing the issue

I2c

### YAML Config

```yaml
substitutions:
  name: brandon-air-1
  friendly_name: Brandon AIR-1
#  ApolloAutomation.AIR-1: github://ApolloAutomation/AIR-1/Integrations/ESPHome/AIR-1.yaml
packages:
  ApolloAutomation.AIR-1:
    url: https://github.com/ApolloAutomation/AIR-1
    ref: main
    files: [Integrations/ESPHome/AIR-1.yaml]
    refresh: 1min
esphome:
  name: ${name}
  name_add_mac_suffix: false
  friendly_name: ${friendly_name}
api:
  encryption:
    key: !secret apollo-air-1-api-key
wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

bluetooth_proxy:
  active: true
esp32_ble_tracker:
  scan_parameters:
    active: false

text_sensor:
  - platform: wifi_info
    ip_address:
      name: "${friendly_name} IP"
      icon: "mdi:ip-outline"

ota:
  platform: esphome
  password: "apolloautomation"

web_server:
  version: 3
```

### Anything in the logs that might be useful for us?

```txt
serial logs attached above
```

**Comment by swoboda1337** [comment]
There were some I2C  see https://github.com/esphome/esphome/pull/10547

Should be fixed in 2025.8.3

**Comment by bharvey88** [comment]
> There were some I2C see [#10547](https://github.com/esphome/esphome/pull/10547)
> 
> Should be fixed in 2025.8.3

This is still happening in 2025.8.3 - serial logs attached

[brandon-air-1_logs.txt](https://github.com/user-attachments/files/22145532/brandon-air-1_logs.txt)

**Comment by AndersRipa** [comment]
Seems to fix my SEN55 problems in Apollo AIR-1
Thank you!
Using ESPHome version 2025.8.4
