### ISSUE TITLE
ESP32-CAM Web Server Failure

### ISSUE THREAD

**Issue by billmaterial** [OttoWinter/esphomeyaml#11255]
### The problem

After updating to 2025.10.0 and uploading, this error is produced in the logs:

[08:51:48.456][I][app:185]: ESPHome version 2025.10.0 compiled on Oct 15 2025, 08:49:17
[08:51:48.475][I][i2c.arduino:099]: Results from bus scan:
[08:51:48.480][I][i2c.arduino:105]: Found device at address 0x30
[08:51:48.701][E][esp32_camera_web_server:099]:   Setup Failed
[08:51:48.701][E][component:154]:   esp32_camera_web_server is marked FAILED: unspecified

### Which version of ESPHome has the issue?

2025.10.0

### What type of installation are you using?

Home Assistant Add-on

### What platform are you using?

ESP32

### Component causing the issue

esp32_camera_web_server

### YAML Config

```yaml
esphome:
  name: esphome-web-xxxxxx
  friendly_name: ESP32-CAM1

esp32:
  board: esp32cam
  framework:
    type: arduino

# Enable logging
logger:
  level: INFO
  logs:
    component: ERROR

# Enable Home Assistant API
api:
  encryption:
    key: "redacted"

ota:
  - platform: esphome
    password: !secret ota_password

wifi:
  networks:
  - ssid: !secret wifi_ssid
    password: !secret wifi_password

captive_portal:
web_server:
    ota: false
esp32_camera_web_server:
  - port: 8080
    mode: stream
  - port: 8081
    mode: snapshot

sensor:
  - platform: wifi_signal # Reports the WiFi signal strength/RSSI in dB
    name: "WiFi Signal dB"
    id: wifi_signal_db
    update_interval: 10s
    entity_category: "diagnostic"

  - platform: internal_temperature
    name: "Internal Temperature"
    id: esp_temperature
    update_interval: 10s
    entity_category: "diagnostic"

text_sensor:
  - platform: wifi_info
    ip_address:
      name: ESP IP Address
    ssid:
      name: ESP Connected SSID
      id: esp_connected_ssid
    bssid:
      name: ESP Connected BSSID
    mac_address:
      name: ESP Mac Wifi Address
    scan_results:
      name: ESP Latest Scan Results 

i2c:
  sda: GPIO26
  scl: GPIO27
  scan: true
  id: bus_a

# ESP32-CAM
esp32_camera:
  external_clock:
    pin: GPIO0
    frequency: 20MHz
  i2c_id:
    bus_a
  data_pins: [GPIO5, GPIO18, GPIO19, GPIO21, GPIO36, GPIO39, GPIO34, GPIO35]
  vsync_pin: GPIO25
  href_pin: GPIO23
  pixel_clock_pin: GPIO22
  power_down_pin: GPIO32

  # Image settings
  name: My ESP32-CAM
  max_framerate: 10fps
  idle_framerate: 0.1fps
  resolution: 800x600
  jpeg_quality: 10 
  vertical_flip: False
  horizontal_mirror: False
  agc_mode: auto
  agc_value: 0
  agc_gain_ceiling: 128x
  wb_mode: auto
  contrast: 0
  brightness: 0
  saturation: 0
  special_effect: none
  test_pattern: False

# Flashlight
output:
  - platform: gpio
    pin: GPIO4
    id: gpio_4

## GPIO_4 is the flash light pin
light:
  - platform: binary
    output: gpio_4
    name: flashlight
## GPIO_33 is the built in LED pin
  - platform: status_led
    name: "LED"
    pin: 
      number: 33
      inverted: True
      mode: OUTPUT
```

### Anything in the logs that might be useful for us?

```txt
[08:51:48.456][I][app:185]: ESPHome version 2025.10.0 compiled on Oct 15 2025, 08:49:17
[08:51:48.475][I][i2c.arduino:099]: Results from bus scan:
[08:51:48.480][I][i2c.arduino:105]: Found device at address 0x30
[08:51:48.701][E][esp32_camera_web_server:099]:   Setup Failed
[08:51:48.701][E][component:154]:   esp32_camera_web_server is marked FAILED: unspecified
```

**Comment by ssieb** [comment]
Get serial logs from boot.  There should be something more.

**Comment by Taomyn** [comment]
Same issue for me, attached is my yaml plus the entire build log

[esp32-s3-sense.yaml](https://github.com/user-attachments/files/22922164/esp32-s3-sense.yaml)

[logs_esp32-s3-sense_run.txt](https://github.com/user-attachments/files/22922167/logs_esp32-s3-sense_run.txt)

**Comment by tOOmki** [comment]
Same problem

**Comment by ssieb** [comment]
The build logs are not useful and those are wireless logs following it.  You need serial logs.

**Comment by Taomyn** [comment]
> The build logs are not useful and those are wireless logs following it. You need serial logs.

Well that's all I have access to

**Comment by billmaterial** [comment]
Serial Log:

[10:30:14]ets Jul 29 2019 12:21:46
[10:30:14]
[10:30:14]rst:0x1 (POWERON_RESET),boot:0x12 (SPI_FAST_FLASH_BOOT)
[10:30:14]configsip: 0, SPIWP:0xee
[10:30:14]clk_drv:0x00,q_drv:0x00,d_drv:0x00,cs0_drv:0x00,hd_drv:0x00,wp_drv:0x00
[10:30:14]mode:DIO, clock div:2
[10:30:14]load:0x3fff0030,len:1184
[10:30:14]load:0x40078000,len:13132
[10:30:14]load:0x40080400,len:3036
[10:30:14]entry 0x400805e4
[10:30:16][I][logger:121]: Log initialized
[10:30:16][I][app:073]: Running through setup()
[10:30:16][I][i2c.arduino:170]: Performing bus recovery
[10:30:19][I][wifi:579]: - 'redacted' [redacted]▂▄▆█
[10:30:19][I][wifi:351]: Connecting to 'redacted'
[10:30:19][W][wifi_esp32:734]: Disconnected ssid='redacted' bssid=[redacted] reason='Authentication Failed'
[10:30:19][W][wifi:734]: Connecting to network failed
[10:30:19][I][wifi:351]: Connecting to 'redacted'
[10:30:19][I][wifi:693]: Connected
[10:30:19][W][wifi:696]: Network 'redacted' should be marked as hidden
[10:30:19][I][esp-idf:000]: E (3555) httpd: httpd_server_init: error in creating msg socket (23)
[10:30:19][E][component:211]: esp32_camera_web_server was marked as failed
[10:30:19][E][component:314]: esp32_camera_web_server set Error flag: unspecified
[10:30:19][I][app:120]: setup() finished successfully!
[10:30:19][I][app:185]: ESPHome version 2025.10.0 compiled on Oct 15 2025, 08:49:17
[10:30:19][I][i2c.arduino:099]: Results from bus scan:
[10:30:19][I][i2c.arduino:101]: Found no devices
[10:30:20][E][esp32_camera_web_server:099]:   Setup Failed
[10:30:20][E][component:154]:   esp32_camera_web_server is marked FAILED: unspecified

**Comment by Taomyn** [comment]
I fixed mine by adding the following to the end of my yaml:

```
psram:
  mode: octal
  speed: 80MHz
```

I also changed the framework so it gets rid of some warnings:

```
esp32:
  board: esp32-s3-devkitc-1
  framework:
    type: esp-idf
```

Be aware, some of these values could be device specific, especially the `psram` values.

**Comment by billmaterial** [comment]
@Taomyn I have added your suggestions but still get the same error:

[14:26:47.959][C][esp32_camera_web_server:088]: ESP32 Camera Web Server:
[14:26:47.959][C][esp32_camera_web_server:088]:   Port: 8080
[14:26:47.961][C][esp32_camera_web_server:093]:   Mode: stream
[14:26:47.966][C][esp32_camera_web_server:088]: ESP32 Camera Web Server:
[14:26:47.966][C][esp32_camera_web_server:088]:   Port: 8081
[14:26:47.986][C][esp32_camera_web_server:095]:   Mode: snapshot
[14:26:47.986][E][esp32_camera_web_server:099]:   Setup Failed
[14:26:47.986][E][component:154]:   esp32_camera_web_server is marked FAILED: unspecified

**Comment by billmaterial** [comment]
I can get it to work if I remove the normal web server on port 80:
web_server:
    ota: false

It looks like you cannot have both the web server and the camera web server working together anymore with the update to 2025.10.0

**Comment by jweston2112** [comment]
I was able to fix mine by adding the sdkconfig_options

Like so:

```yaml
  framework:
    type: esp-idf
    version: recommended
    sdkconfig_options:
      CONFIG_LWIP_MAX_SOCKETS: "16"
```
I can use both the on port 80 and stream 8080 and snapshot 8081

Hope this helps

**Comment by bdraco** [comment]
> [10:30:19][I][esp-idf:000]: E (3555) httpd: httpd_server_init: error in creating msg socket (23)

Error 23 typically indicates "Too many open files" or socket exhaustion.

https://github.com/esphome/esphome/issues/11255#issuecomment-3419254928 is likely the best solution

2025.10.x changed to Arduino as an IDF component. It was likely that the default CONFIG_LWIP_MAX_SOCKETS was higher before as ESP-IDF only allows 10 by default

**Comment by pksoft585** [comment]
to **jweston2112**: it works... Thank you.

**Comment by billmaterial** [comment]
@jweston2112 I can confirm it works too, thanks ;)
