### ISSUE TITLE
Update Esp32cam via ESPHome Builder failed. fatal: not a git repository (or any parent up to mount point /)

### ISSUE THREAD

**Issue by perlchamp** [OttoWinter/esphomeyaml#11997]
### The problem

While updating my esp32cam device there is an error:
git rev-parse returned 'fatal: not a git repository (or any parent up to mount point /)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).'

### Which version of ESPHome has the issue?

Installationsmethode Home Assistant OS 
Core 2025.11.2 
Supervisor 2025.11.3 
Operating System 16.3 Frontend 20251105.0
ESPHome  2025.10.5

### What type of installation are you using?

Home Assistant Add-on

### What platform are you using?

ESP32, ESP8266

### Component causing the issue

ESPHome Builder, ESP32cam

### YAML Config

```
esphome:
  name: esp-32scam-ip58
  friendly_name: ESP-32SCAM-IP58

esp32:
  board: esp32dev
  framework:
    type: arduino

# Enable logging
logger:
  level: VERBOSE                                       
  tx_buffer_size: 256                                  

# Enable Home Assistant API
api:
  encryption:
    key: "IKPtYwrvmKMyYAmbppXjRKsdfUvr0chUNrPVGjuXIBcR3Q="

ota:
  - platform: esphome
    password: "8532486f3fc9600sdf40264704985997b22"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  domain: ".local"
  power_save_mode: none
  manual_ip:
    static_ip: 192.168.178.XXX
    gateway: 192.168.178.XXX
    subnet: 255.255.255.0
    dns1: 192.168.178.XXX
    dns2: 0.0.0.0

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Esp-32Scam-Ip58 Fallback Hotspot"
    password: "3wwdsfgeb6AORkY77v"

captive_portal:

output:
- platform: ledc
  pin: GPIO4
  id: gpio_4
  channel: 2

light:
  - platform: monochromatic
    output: gpio_4
    name: Flash/PWM Light
    restore_mode: ALWAYS_OFF
    
i2c:
  - id: cam1_wz_i2c
    sda: GPIO26
    scl: GPIO27
  
esp32_camera:
  name: CAM1-WZ
  i2c_id: cam1_wz_i2c
  external_clock:
    pin: GPIO0
    frequency: 20MHz
  data_pins: [GPIO5, GPIO18, GPIO19, GPIO21, GPIO36, GPIO39, GPIO34, GPIO35]
  vsync_pin: GPIO25
  href_pin: GPIO23
  pixel_clock_pin: GPIO22
  power_down_pin: GPIO32
  
# Image settings
  resolution: 640x480                      # 400x296, max: 800x600 (Hitze !)
  jpeg_quality: 10                         # gut:10 bis schlecht:63
  max_framerate: 10fps
  idle_framerate: 0.1fps
  vertical_flip: false
  horizontal_mirror: false
  contrast: 2                                # -2 to 2
  brightness: 2                            # -2 to 2
  saturation: 1
  special_effect: none

  ## -- exposure -- ##
  aec_mode: manual                     # wenn 'manual', dann auch Wert für 'aec_value' setzen
  aec_value: 1200                          # 0-1200
  #aec2: true                              

  ## -- gain -- ##
  agc_mode: manual                     # wenn 'manual', dann auch Wert für 'agc_value' setzen
  agc_value: 8                                # 0-30
  agc_gain_ceiling: 32x                    

  ## -- white balance -- ##
  wb_mode: cloudy

# Debugging
#  test_pattern: true

```

### Anything in the logs that might be useful for us?

```
Installing Arduino Python dependencies
Creating a new virtual environment for IDF Python dependencies
Installing ESP-IDF's Python dependencies
Reading CMake configuration...
-- Found Git: /usr/bin/git (found version "2.39.5")
-- git rev-parse returned 'fatal: not a git repository (or any parent up to mount point /)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).'
-- The C compiler identification is unknown
-- The CXX compiler identification is unknown
-- The ASM compiler identification is unknown
-- Found assembler: xtensa-esp32-elf-gcc
-- Warning: Did not find file Compiler/-ASM
-- Configuring incomplete, errors occurred!

fatal: not a git repository (or any parent up to mount point /)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
CMake Error at /data/cache/platformio/packages/framework-espidf/tools/cmake/project.cmake:571 (__project):
  The CMAKE_C_COMPILER:

    xtensa-esp32-elf-gcc

  is not a full path and was not found in the PATH.

  Tell CMake where to find the compiler by setting either the environment
  variable "CC" or the CMake cache entry CMAKE_C_COMPILER to the full path to
  the compiler, or to the compiler name if it is in the PATH.
Call Stack (most recent call first):
  CMakeLists.txt:3 (project)


CMake Error at /data/cache/platformio/packages/framework-espidf/tools/cmake/project.cmake:571 (__project):
  The CMAKE_CXX_COMPILER:

    xtensa-esp32-elf-g++

  is not a full path and was not found in the PATH.

  Tell CMake where to find the compiler by setting either the environment
  variable "CXX" or the CMake cache entry CMAKE_CXX_COMPILER to the full path
  to the compiler, or to the compiler name if it is in the PATH.
Call Stack (most recent call first):
  CMakeLists.txt:3 (project)


CMake Error at /data/cache/platformio/packages/framework-espidf/tools/cmake/project.cmake:571 (__project):
  The CMAKE_ASM_COMPILER:

    xtensa-esp32-elf-gcc

  is not a full path and was not found in the PATH.

  Tell CMake where to find the compiler by setting either the environment
  variable "ASM" or the CMake cache entry CMAKE_ASM_COMPILER to the full path
  to the compiler, or to the compiler name if it is in the PATH.
Call Stack (most recent call first):
  CMakeLists.txt:3 (project)

```

### Additional information

Restarting or/and Reinstalling ESPHome Builder didn't solve the problem

**Comment by swoboda1337** [comment]
Normally happens if you run two builds at once, hit stop or close the window while installing the tools. Run "Clean all" at the top right beside "Update All"

**Comment by perlchamp** [comment]
Hi, hallo.
Thanks for your answer. 
Info: Not all devices are online. This is what i wanted.
So i click on the 3-Point-Button did choose 'clean build files' of one of the devices which are online.

```
INFO ESPHome 2025.10.5
INFO Reading configuration /config/esphome/esp-32scam-ip58.yaml...
WARNING GPIO0 is a strapping PIN and should only be used for I/O with care.
Attaching external pullup/down resistors to strapping pins can cause unexpected failures.
See https://esphome.io/guides/faq.html#why-am-i-getting-a-warning-about-strapping-pins
WARNING GPIO5 is a strapping PIN and should only be used for I/O with care.
Attaching external pullup/down resistors to strapping pins can cause unexpected failures.
See https://esphome.io/guides/faq.html#why-am-i-getting-a-warning-about-strapping-pins
INFO Deleting /data/build/esp-32scam-ip58/.pioenvs
INFO Deleting /data/build/esp-32scam-ip58/.piolibdeps
INFO Deleting PlatformIO cache /data/cache/platformio/cache
INFO Done!
```

I restarted HA and then i went to the ESPHome Builder, pressed strg+f5.
Then i click on the 3-point-Button of the device which is online and take 'install' --> wirelessly.

That didn't solve the problem:

```
INFO ESPHome 2025.10.5
INFO Reading configuration /config/esphome/esp-32scam-ip58.yaml...
WARNING GPIO0 is a strapping PIN and should only be used for I/O with care.
Attaching external pullup/down resistors to strapping pins can cause unexpected failures.
See https://esphome.io/guides/faq.html#why-am-i-getting-a-warning-about-strapping-pins
WARNING GPIO5 is a strapping PIN and should only be used for I/O with care.
Attaching external pullup/down resistors to strapping pins can cause unexpected failures.
See https://esphome.io/guides/faq.html#why-am-i-getting-a-warning-about-strapping-pins
INFO Generating C++ source...
INFO Compiling app...
Processing esp-32scam-ip58 (board: esp32dev; framework: arduino, espidf; platform: https://github.com/pioarduino/platform-espressif32/releases/download/54.03.21-2/platform-espressif32.zip)
--------------------------------------------------------------------------------
INFO Package configuration completed successfully
Library Manager: Installing esphome/noise-c @ 0.1.10
INFO Installing esphome/noise-c @ 0.1.10
Downloading  [####################################]  100%
Unpacking  [####################################]  100%
Library Manager: noise-c@0.1.10 has been installed!
INFO noise-c@0.1.10 has been installed!
Library Manager: Resolving dependencies...
INFO Resolving dependencies...
Library Manager: Installing esphome/libsodium @ 1.10020.7
INFO Installing esphome/libsodium @ 1.10020.7
Downloading  [####################################]  100%
Unpacking  [####################################]  100%
Library Manager: libsodium@1.10020.7 has been installed!
INFO libsodium@1.10020.7 has been installed!
INFO Package configuration completed successfully
HARDWARE: ESP32 240MHz, 320KB RAM, 4MB Flash
 - framework-arduinoespressif32 @ 3.2.1 
 - framework-arduinoespressif32-libs @ 5.4.0+sha.858a988d6e 
 - framework-espidf @ 3.50402.0 (5.4.2) 
 - tool-cmake @ 3.30.2 
 - tool-esp-rom-elfs @ 2024.10.11 
 - tool-esptoolpy @ 5.0.2 
 - tool-mklittlefs @ 3.2.0 
 - tool-ninja @ 1.13.1 
 - tool-scons @ 4.40801.0 (4.8.1) 
 - toolchain-xtensa-esp-elf @ 14.2.0+20241119
Reading CMake configuration...
-- Found Git: /usr/bin/git (found version "2.39.5")
-- git rev-parse returned 'fatal: not a git repository (or any parent up to mount point /)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).'
-- The C compiler identification is unknown
-- The CXX compiler identification is unknown
-- The ASM compiler identification is unknown
-- Found assembler: xtensa-esp32-elf-gcc
-- Warning: Did not find file Compiler/-ASM
-- Configuring incomplete, errors occurred!

fatal: not a git repository (or any parent up to mount point /)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
CMake Error at /data/cache/platformio/packages/framework-espidf/tools/cmake/project.cmake:571 (__project):
  The CMAKE_C_COMPILER:

    xtensa-esp32-elf-gcc

  is not a full path and was not found in the PATH.

  Tell CMake where to find the compiler by setting either the environment
  variable "CC" or the CMake cache entry CMAKE_C_COMPILER to the full path to
  the compiler, or to the compiler name if it is in the PATH.
Call Stack (most recent call first):
  CMakeLists.txt:3 (project)


CMake Error at /data/cache/platformio/packages/framework-espidf/tools/cmake/project.cmake:571 (__project):
  The CMAKE_CXX_COMPILER:

    xtensa-esp32-elf-g++

  is not a full path and was not found in the PATH.

  Tell CMake where to find the compiler by setting either the environment
  variable "CXX" or the CMake cache entry CMAKE_CXX_COMPILER to the full path
  to the compiler, or to the compiler name if it is in the PATH.
Call Stack (most recent call first):
  CMakeLists.txt:3 (project)


CMake Error at /data/cache/platformio/packages/framework-espidf/tools/cmake/project.cmake:571 (__project):
  The CMAKE_ASM_COMPILER:

    xtensa-esp32-elf-gcc

  is not a full path and was not found in the PATH.

  Tell CMake where to find the compiler by setting either the environment
  variable "ASM" or the CMake cache entry CMAKE_ASM_COMPILER to the full path
  to the compiler, or to the compiler name if it is in the PATH.
Call Stack (most recent call first):
  CMakeLists.txt:3 (project)



========================= [FAILED] Took 14.00 seconds =========================
```

**Comment by swoboda1337** [comment]
Not "Clean build files" I said "Clean All"

<img width="524" height="171" alt="Image" src="https://github.com/user-attachments/assets/76e2c586-a8a5-4f1b-a0f8-5affded23c6f" />

**Comment by perlchamp** [comment]
Hi, thanks for your answer.
I did click on 'clean all', but nothing happened, means, i didn't see a popup, no information about what happens, nothing. (How said: not all devices were online). 
After that the same procedure: restart ha, strg+f5 and the try to update the cam. Same result:

```
INFO ESPHome 2025.10.5
INFO Reading configuration /config/esphome/esp-32scam-ip58.yaml...
WARNING GPIO0 is a strapping PIN and should only be used for I/O with care.
Attaching external pullup/down resistors to strapping pins can cause unexpected failures.
See https://esphome.io/guides/faq.html#why-am-i-getting-a-warning-about-strapping-pins
WARNING GPIO5 is a strapping PIN and should only be used for I/O with care.
Attaching external pullup/down resistors to strapping pins can cause unexpected failures.
See https://esphome.io/guides/faq.html#why-am-i-getting-a-warning-about-strapping-pins
INFO Generating C++ source...
INFO Compiling app...
Processing esp-32scam-ip58 (board: esp32dev; framework: arduino, espidf; platform: https://github.com/pioarduino/platform-espressif32/releases/download/54.03.21-2/platform-espressif32.zip)
--------------------------------------------------------------------------------
INFO Package configuration completed successfully
INFO Package configuration completed successfully
HARDWARE: ESP32 240MHz, 320KB RAM, 4MB Flash
 - framework-arduinoespressif32 @ 3.2.1 
 - framework-arduinoespressif32-libs @ 5.4.0+sha.858a988d6e 
 - framework-espidf @ 3.50402.0 (5.4.2) 
 - tool-cmake @ 3.30.2 
 - tool-esp-rom-elfs @ 2024.10.11 
 - tool-esptoolpy @ 5.0.2 
 - tool-mklittlefs @ 3.2.0 
 - tool-ninja @ 1.13.1 
 - tool-scons @ 4.40801.0 (4.8.1) 
 - toolchain-xtensa-esp-elf @ 14.2.0+20241119
Reading CMake configuration...
-- git rev-parse returned 'fatal: not a git repository (or any parent up to mount point /)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).'
-- The C compiler identification is unknown
-- The CXX compiler identification is unknown
-- The ASM compiler identification is unknown
-- Found assembler: xtensa-esp32-elf-gcc
-- Warning: Did not find file Compiler/-ASM
-- Configuring incomplete, errors occurred!

fatal: not a git repository (or any parent up to mount point /)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
CMake Error at /data/cache/platformio/packages/framework-espidf/tools/cmake/project.cmake:571 (__project):
  The CMAKE_C_COMPILER:

    xtensa-esp32-elf-gcc

  is not a full path and was not found in the PATH.

  Tell CMake where to find the compiler by setting either the environment
  variable "CC" or the CMake cache entry CMAKE_C_COMPILER to the full path to
  the compiler, or to the compiler name if it is in the PATH.
Call Stack (most recent call first):
  CMakeLists.txt:3 (project)


CMake Error at /data/cache/platformio/packages/framework-espidf/tools/cmake/project.cmake:571 (__project):
  The CMAKE_CXX_COMPILER:

    xtensa-esp32-elf-g++

  is not a full path and was not found in the PATH.

  Tell CMake where to find the compiler by setting either the environment
  variable "CXX" or the CMake cache entry CMAKE_CXX_COMPILER to the full path
  to the compiler, or to the compiler name if it is in the PATH.
Call Stack (most recent call first):
  CMakeLists.txt:3 (project)


CMake Error at /data/cache/platformio/packages/framework-espidf/tools/cmake/project.cmake:571 (__project):
  The CMAKE_ASM_COMPILER:

    xtensa-esp32-elf-gcc

  is not a full path and was not found in the PATH.

  Tell CMake where to find the compiler by setting either the environment
  variable "ASM" or the CMake cache entry CMAKE_ASM_COMPILER to the full path
  to the compiler, or to the compiler name if it is in the PATH.
Call Stack (most recent call first):
  CMakeLists.txt:3 (project)



========================== [FAILED] Took 8.20 seconds ==========================
```

This didn't solve the problem :-(

Do you have some other ideas?
Thanks for your time.

**Comment by swoboda1337** [comment]
Clean all will bring up a pop up then a dialog. Try a different browser or your phone? Seems like your browser is blocking it. Does update all do anything?

The only other choice is to uninstall the add-on, make sure to click remove data and then reinstall it

**Comment by perlchamp** [comment]
Hi, hallo. Thanks for your answer.
After a while i cklicked on the 'clean all'-button again, and this time a window popped up:

EDIT:
maybe i should restart ESPHome Builder, too (the next time)
edit end

```
INFO Cleaning /data
INFO Deleting PlatformIO core_dir /root/.platformio
INFO Done!
```
I did close it, restarted HA, strg+f5 and started the installation of the cam. It's still running now, i will report.

By the way:
The cause why i didn't click 'clean all' was:
a long time ago, i clicked on 'update all' and then it tried to update the offline devices, too. What a chaos that was...

**Comment by swoboda1337** [comment]
> The cause why i didn't click 'clean all' was: a long time ago, i clicked on 'update all' and then it tried to update the offline devices, too. What a chaos that was...

Yeah clean all doesn't care about devices at all it just cleans those folders. It should work now.

**Comment by perlchamp** [comment]
Thanks for your answer. It's still running.
The only warning i got until yet (it's more an info instead of a warning, i think. Sounds well):
```
In file included from managed_components/espressif__esp_diagnostics/src/esp_diagnostics_utils.c:52:
/data/cache/platformio/packages/framework-espidf/components/freertos/esp_additions/include/freertos/task_snapshot.h:8:2: warning: #warning freertos/task_snapshot.h header is no longer used, and will be removed in future versions. [-Wcpp]
    8 | #warning freertos/task_snapshot.h header is no longer used, and will be removed in future versions.
      |  ^~~~~~~
```

**Comment by perlchamp** [comment]
Touchdown :-)
Yes it works. Many thanks. You're my hero of the day.

By the way (off topic):
the behavior of the 'update all' button is still the same (try to update offline devices) ?
I'm angry to test that...

Many thanks again.
