### ISSUE TITLE
can't compile 2025.12.3 ModuleNotFoundError: No module named 'idf_component_manager'

### ISSUE THREAD

**Issue by turboc1208** [OttoWinter/esphomeyaml#12767]
### The problem

can't compile multiple applications with error 

### Which version of ESPHome has the issue?

2025.12.3

### What type of installation are you using?

Home Assistant Add-on

### What platform are you using?

ESP32

### Component causing the issue

epslite, ratgdo, esphome

### YAML Config

```yaml
substitutions:
  name: eplite-breakfastroom
  friendly_name: eplite-breakfastroom
packages:
  EverythingSmartTechnology.Everything_Presence_Lite: github://everythingsmarthome/everything-presence-lite/everything-presence-lite-ha.yaml@main
esphome:
  name: ${name}
  name_add_mac_suffix: false
  friendly_name: ${friendly_name}
api:
  encryption:
    key: Qzpbc+qGdaQ1nCRRJf4A4C2Fc46zqI6Cx0GsfawWHBU=

wifi:
  ssid: !secret wifi_iot_ssid
  password: !secret wifi_iot_password
  power_save_mode: none
  use_address: ${name}
  domain: .home.fs.com

#web_server:
#  port: 80

ota:
  - platform: esphome  # Your existing OTA method
#  - platform: web_server  # Add this for web-based OTA uploads
```

### Anything in the logs that might be useful for us?

```txt
Reading CMake configuration...
-- git rev-parse returned 'fatal: not a git repository (or any parent up to mount point /)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).'
-- Minimal build - OFF
-- Building ESP-IDF components for target esp32
-- Configuring incomplete, errors occurred!

fatal: not a git repository (or any parent up to mount point /)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
CMake Error at /data/cache/platformio/packages/framework-espidf/tools/cmake/build.cmake:629 (message):
  /root/.platformio/penv/.espidf-5.5.1/bin/python: Error while finding module
  specification for 'idf_component_manager.prepare_components'
  (ModuleNotFoundError: No module named 'idf_component_manager')

Call Stack (most recent call first):
  /data/cache/platformio/packages/framework-espidf/tools/cmake/project.cmake:740 (idf_build_process)
  CMakeLists.txt:3 (project)
```

**Comment by PaulBiod** [comment]
The same here

**Comment by Guillembonet** [comment]
I have the same, I tried downgrading to 2025.12.1 and got the same result

**Comment by turulix** [comment]
having the same issue, downgraded to 2025.12.2 just to test and still had the issue, interestingly enough idf_component_manager is being build from source, which fails because gcc can't be found.

Manually executing `apt-get install build-essential` inside the docker container i'm running it in and clearing cache resolves the issue (clearing the cache after installing build-essential)

---

Also upgraded back to 2025.12.3
[logs.txt](https://github.com/user-attachments/files/24397079/logs.txt)

---

This might actually be an upstream issue with: https://sourceforge.net/p/ruamel-yaml/code/ci/default/tree/ version 0.19.0 which, well. Was released 2 hours ago :D

**Comment by lastb0isct** [comment]
Yeah, I have the exact same issue.  Here is my build log if that helps when initially installing.

[logs_espa_compile.txt](https://github.com/user-attachments/files/24397060/logs_espa_compile.txt)

**Comment by SpicyLimes** [comment]
I had the same issue as everyone above but I was able to correct the issue. Since I am running ESPHome in a Docker Container via Portainer, I used the `ssh` function within the container to run `apt update && apt upgrade -y` then `apt-get install build-essential`. I restarted the Container (2025.12.3 version), did a "CLEAN ALL" within the Device Builder WebUI, and BOOM - all is working as it should. 

Hope this helps.

EDIT: For those using Docker, it might also be necessary to delete any cached files within the `.esphome` directory where your config files are. WARNING: Make a copy of the folder first before removing anything - just good common sense in case something else breaks.

**Comment by szczupak-offi** [comment]
ad how can i fix it when i am not running it in docker?

**Comment by lastb0isct** [comment]
None of the fixes above worked for me in my docker compose/docker container sadly.  I guess i'll be waiting for an official fix.  Just my luck, first time trying to install esphome to an esp32 device and this is the error I get haha

EDIT: Works now!

**Comment by lee13se** [comment]
> I had the same issue as everyone above but I was able to correct the issue. Since I am running ESPHome in a Docker Container via Portainer, I used the `ssh` function within the container to run `apt update && apt upgrade -y` then `apt-get install build-essential`. I restarted the Container (2025.12.3 version), did a "CLEAN ALL" within the Device Builder WebUI, and BOOM - all is working as it should.

Thank you, this worked for me.  First I tried apt-get build-essential and Clean All, but that was not enough.  I had to runt apt-get update/upgrade.


> EDIT: For those using Docker, it might also be necessary to delete any cached files within the `.esphome` directory where your config files are. WARNING: Make a copy of the folder first before removing anything - just good common sense in case something else breaks.

I didn't need to do this.

**Comment by ndrwrbgs** [comment]
@turulix work around worked for me, but it's precarious given it relies on setting custom global state in a docker image - so if viewers do that keep in mind you may need to do it again later.

Getting into the container: You don't need to be running docker necessarily, 1 example: HA runs add-ons in docker and that's the docker you'd want to get into. If you were running bare metal than you'd run the commands directly on your machine. Basically, for now, you need to get the build tool `gcc` into the environment.
```
HomeAssistant specific
  1. Get a terminal on your HA instance
  2. If it prompts with `ha >` type `login`
  3. `docker ps | grep esp` to identify the name. It will be like `addon_5c512345_esphome`
  4. `docker exec -it addon_5c512345_esphome /bin/bash` to get inside of that container
General
  6. `apt-get update` to update package information
  7. `apt-get install build-essential` [done with the consoles]
  8. Clean build files in ESPHome UI (it seems to not fully "recognize" the failure, and so does not retry that step even with the new build dependencies present)
  9. Try again
```

**Comment by ndrwrbgs** [comment]
<details>
<summary>details for maintainers not users</summary>

It seems the source is that [idf-component-manager](https://github.com/espressif/idf-component-manager/blob/main/pyproject.toml) imports latest of ruamel.yaml, which in v0.19.0 [12/31/2025] [link](https://sourceforge.net/p/ruamel-yaml/code/ci/2a6a9c57228d5ae1e3e8b550c461128888e058ce/) stopped coming with a pre-compiled version and now needs a compiler environment pre-installed.


--- Update from reading the docs ---
> The C sources are functionally unchanged,
> but they are now always compiled (using `setuptools-zig` and `ziglang`) on your system,
> instead of being downloaded as pre-compiled wheels (if available).
> For this to function properly your Python (virtual) environment needs to have
> an up-to-date version of `setuptools` and `wheels` pre-installed.
> 
> If you run into trouble, you can install `ruamel.yaml.clib` explicitly, without
> using `ruamel.yaml.clibz` at all, using:
> 
> 
> ```
>     python -m pip install --no-deps ruamel.yaml ruamel.yaml.clib

</details>

**Comment by szczupak-offi** [comment]
> [@turulix](https://github.com/turulix)
thanks worked for me

**Comment by lastb0isct** [comment]
I take it back...fix worked for me now.  Had to start fresh again, but now working!

**Comment by svalcken** [comment]
Since Version 2025.12.3 (today) Update, i have the same issue.
I have tried an bluetooth-Proxy as config, the same on other esp Device with relais.

This does not work for me.

I have tried after clean build from UI, validate (okay) and than install via WEB.
I stopped durian build.

Here by Log from Build:

```INFO ESPHome 2025.12.3
INFO Reading configuration /config/esphome/ble-proxy-01.yaml...
INFO Generating C++ source...
INFO Setting CONFIG_LWIP_MAX_SOCKETS to 14 (registered: api=4, captive_portal=4, mdns=2, ota=1, web_server=3)
INFO Compiling app... Build path: /data/build/ble-proxy-01
Processing ble-proxy-01 (board: esp32dev; framework: espidf; platform: https://github.com/pioarduino/platform-espressif32/releases/download/55.03.31-2/platform-espressif32.zip)
--------------------------------------------------------------------------------
Library Manager: Installing esphome/noise-c @ 0.1.10
INFO Installing esphome/noise-c @ 0.1.10
Downloading  [####################################]  100%
Unpacking  [####################################]  100%
Library Manager: noise-c@0.1.10 has been installed!
INFO noise-c@0.1.10 has been installed!
Library Manager: Resolving dependencies...
INFO Resolving dependencies...
Library Manager: Installing esphome/libsodium @ 1.10020.7
INFO Installing esphome/libsodium @ 1.10020.7
Downloading  [####################################]  100%
Unpacking  [####################################]  100%
Library Manager: libsodium@1.10020.7 has been installed!
INFO libsodium@1.10020.7 has been installed!
Library Manager: Installing bblanchon/ArduinoJson @ 7.4.2
INFO Installing bblanchon/ArduinoJson @ 7.4.2
Downloading  [####################################]  100%
Unpacking  [####################################]  100%
Library Manager: ArduinoJson@7.4.2 has been installed!
INFO ArduinoJson@7.4.2 has been installed!
HARDWARE: ESP32 240MHz, 320KB RAM, 4MB Flash
 - contrib-piohome @ 3.4.4 
 - framework-espidf @ 3.50501.0 (5.5.1) 
 - tool-cmake @ 4.0.3 
 - tool-esp-rom-elfs @ 2024.10.11 
 - tool-esptoolpy @ 5.1.0 
 - tool-mklittlefs @ 3.2.0 
 - tool-ninja @ 1.13.1 
 - tool-scons @ 4.40801.0 (4.8.1) 
 - toolchain-xtensa-esp-elf @ 14.2.0+20241119
Reading CMake configuration...
-- Found Git: /usr/bin/git (found version "2.39.5")
-- git rev-parse returned 'fatal: not a git repository (or any parent up to mount point /)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).'
-- Minimal build - OFF
-- The C compiler identification is GNU 14.2.0
-- The CXX compiler identification is GNU 14.2.0
-- The ASM compiler identification is GNU
-- Found assembler: /data/cache/platformio/packages/toolchain-xtensa-esp-elf/bin/xtensa-esp32-elf-gcc
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /data/cache/platformio/packages/toolchain-xtensa-esp-elf/bin/xtensa-esp32-elf-gcc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /data/cache/platformio/packages/toolchain-xtensa-esp-elf/bin/xtensa-esp32-elf-g++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Building ESP-IDF components for target esp32
-- Configuring incomplete, errors occurred!

fatal: not a git repository (or any parent up to mount point /)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
CMake Error at /data/cache/platformio/packages/framework-espidf/tools/cmake/build.cmake:629 (message):
  /root/.platformio/penv/.espidf-5.5.1/bin/python: Error while finding module
  specification for 'idf_component_manager.prepare_components'
  (ModuleNotFoundError: No module named 'idf_component_manager')

Call Stack (most recent call first):
  /data/cache/platformio/packages/framework-espidf/tools/cmake/project.cmake:740 (idf_build_process)
  CMakeLists.txt:3 (project)
========================= [FAILED] Took 68.08 seconds =========================
```


> [@turulix](https://github.com/turulix) work around worked for me, but it's precarious given it relies on setting custom global state in a docker image - so if viewers do that keep in mind you may need to do it again later.
> 
> Getting into the container: You don't need to be running docker necessarily, 1 example: HA runs add-ons in docker and that's the docker you'd want to get into. If you were running bare metal than you'd run the commands directly on your machine. Basically, for now, you need to get the build tool `gcc` into the environment.
> 
> ```
> HomeAssistant specific
>   1. Get a terminal on your HA instance
>   2. If it prompts with `ha >` type `login`
>   3. `docker ps | grep esp` to identify the name. It will be like `addon_5c512345_esphome`
>   4. `docker exec -it addon_5c512345_esphome /bin/bash` to get inside of that container
> General
>   6. `apt-get update` to update package information
>   7. `apt-get install build-essential` [done with the consoles]
>   8. Clean build files in ESPHome UI (it seems to not fully "recognize" the failure, and so does not retry that step even with the new build dependencies present)
>   9. Try again
> ```

**Comment by ebmarquez** [comment]
Same issue happening with my device also.  See attached logs and config.

[logs_garage-door-opener_run-outout.txt](https://github.com/user-attachments/files/24397665/logs_garage-door-opener_run-outout.txt)

**Comment by turboc1208** [comment]
worked for me.  Thanks for the step by step instructions.

**Comment by astrosteve0** [comment]
Same here. I tried a Clean All, didn't help. I tried uninstalling ESPHome and reinstalling it - didn't help.

UPDATE - The great instructions by [ndrwrbgs](https://github.com/ndrwrbgs) worked for me.

**Comment by reidcooper** [comment]
I followed the instructions shared above here: https://github.com/esphome/esphome/issues/12767#issuecomment-3702742646

This worked for me, you need to install the missing packages inside the docker container that is running - wherever you have it.

**Comment by kdmukai** [comment]
> This might actually be an upstream issue with: https://sourceforge.net/p/ruamel-yaml/code/ci/default/tree/ version 0.19.0 which, well. Was released 2 hours ago :D

Ug, what a mess. Had to do some dependency digging.

`ruamel.yaml` IS properly being pinned to `0.18.16`:

https://github.com/esphome/esphome/blob/2025.12.3/requirements.txt#L18-L19

However, error logs are clear, especially the very end:
```
  × Failed to build `ruamel-yaml-clibz==0.3.4`
  ├─▶ The build backend returned an error
  ╰─▶ Call to `setuptools.build_meta:__legacy__.build_wheel` failed (exit
      status: 1)

      [stdout]
      running bdist_wheel
      running build
      running build_ext
      building '_ruamel_yaml_clibz' extension
      creating build/temp.linux-x86_64-cpython-312
      gcc -fno-strict-overflow -Wsign-compare -DNDEBUG -g -O3
      -Wall -fPIC -I/root/.cache/uv/builds-v0/.tmpVXUiGJ/include
      -I/usr/local/include/python3.12 -c _ruamel_yaml_clibz.c -o
      build/temp.linux-x86_64-cpython-312/_ruamel_yaml_clibz.o

      [stderr]
      /root/.cache/uv/builds-v0/.tmpVXUiGJ/lib/python3.12/site-packages/setuptools/_distutils/dist.py:289:
      UserWarning: Unknown distribution option: 'build_zig'
        warnings.warn(msg)
      error: command 'gcc' failed: No such file or directory

      hint: This usually indicates a problem with the package or the build
      environment.
  help: `ruamel-yaml-clibz` (v0.3.4) was included because
        `idf-component-manager` (v2.4.3) depends on `ruamel-yaml` (v0.19.0)
        which depends on `ruamel-yaml-clibz`
```

But if we dig into `idf-component-manager`, it is just listing `ruamel.yaml` ("dot" not "dash"; and has no pinned version):

https://github.com/espressif/idf-component-manager/blob/v2.4.3/pyproject.toml#L40

So... where is it picking up the "dash" `ruamel-yaml` dependency that's reported in the error?!!

Okay, did some tests. It's pypi. The library maintainer mentions possible problems with having the "dot" in the namespace. I'm guessing that he created the "dash" namespace as a future migration. Or something...?

So maybe:
* `idf-component-manager`'s `ruamel.yaml` dependency is being escaped to `ruamel-yaml` ("dot" to "dash") when it's processed.
* That namespace diff then defeats ESPHome's pinned `ruamel.yaml==0.18.16`.
* And so we end up fetching `ruamel-yaml` which currently defaults to  v0.19.0.
* And we know v0.19.0 has the problematic `ruamel-yaml-clibz` dependency.

Misc `pip` tests:
`pip install ruamel-yaml` -> `ruamel.yaml==0.19.0`  <--THIS IS OUR PROBLEM
`pip install ruamel.yaml` (no version specified) -> `ruamel.yaml==0.19.0`
`pip install ruamel.yaml==0.18.16` -> `ruamel.yaml==0.18.16`  <--This is what we expect

**Comment by molusk** [comment]
> Misc `pip` tests: 
> `pip install ruamel-yaml` -> `ruamel.yaml==0.19.0` <--THIS IS OUR PROBLEM 
> `pip install ruamel.yaml` (no version specified) -> `ruamel.yaml==0.19.0` 
> `pip install ruamel.yaml==0.18.16` -> `ruamel.yaml==0.18.16` <--This is what we expect

Pinning ruamel-yaml to version 0.18.16 seems doable :
```bash
$ pip install ruamel-yaml==0.18.16
Collecting ruamel-yaml==0.18.16
  Downloading ruamel.yaml-0.18.16-py3-none-any.whl.metadata (25 kB)
Collecting ruamel.yaml.clib>=0.2.7 (from ruamel-yaml==0.18.16)
  Downloading ruamel_yaml_clib-0.2.15-cp313-cp313-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl.metadata (3.5 kB)
Downloading ruamel.yaml-0.18.16-py3-none-any.whl (119 kB)
Downloading ruamel_yaml_clib-0.2.15-cp313-cp313-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl (782 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 782.1/782.1 kB 30.2 MB/s eta 0:00:00
Installing collected packages: ruamel.yaml.clib, ruamel-yaml
Successfully installed ruamel-yaml-0.18.16 ruamel.yaml.clib-0.2.15
```

**Comment by spydazcomputers** [comment]
I removed the ESPHOME Addon and Re-installed it and it is working.

**Comment by ssieb** [comment]
Probably because you picked up the new release.

**Comment by ndrwrbgs** [comment]
RE: https://github.com/esphome/esphome/issues/12767#issuecomment-3702901088
This particular failure issue (the one the OP hit) was fixed in #12769 and [released a few hours ago](https://github.com/esphome/esphome/releases/tag/2025.12.4)
Thanks @bdraco

**Comment by melgu** [comment]
I'm on 2025.12.4 and the error is still present.

I'm on Windows with Python version 3.13.11.

<details>

<summary>Command Line Logs</summary>

```
PS D:\Programme\ESPHome> esphome compile sensecap-indicator-1.yaml
INFO ESPHome 2025.12.4
INFO Reading configuration sensecap-indicator-1.yaml...
INFO Generating C++ source...
INFO Compiling app... Build path: D:\Programme\ESPHome\.esphome\build\sensecap-indicator-1
Processing sensecap-indicator-1 (board: esp32-s3-devkitc-1; framework: espidf; platform: https://github.com/pioarduino/platform-espressif32/releases/download/55.03.31-2/platform-espressif32.zip)
---------------------------------------------------------------------------------------------------------------------------------------------------------------------Verbose mode can be enabled via `-v, --verbose` option
CONFIGURATION: https://docs.platformio.org/page/boards/espressif32/esp32-s3-devkitc-1.html
PLATFORM: Espressif 32 (55.3.31) > Espressif ESP32-S3-DevKitC-1-N8 (8 MB QD, No PSRAM)
HARDWARE: ESP32S3 240MHz, 320KB RAM, 8MB Flash
DEBUG: Current (esp-builtin) On-board (esp-builtin) External (cmsis-dap, esp-bridge, esp-prog, iot-bus-jtag, jlink, minimodule, olimex-arm-usb-ocd, olimex-arm-usb-ocd-h, olimex-arm-usb-tiny-h, olimex-jtag-tiny, tumpa)
PACKAGES:
 - contrib-piohome @ 3.4.4
 - framework-espidf @ 3.50501.0 (5.5.1)
 - tool-cmake @ 4.0.3
 - tool-esp-rom-elfs @ 2024.10.11
 - tool-esptoolpy @ 5.1.0
 - tool-mklittlefs @ 3.2.0
 - tool-ninja @ 1.13.1
 - tool-scons @ 4.40801.0 (4.8.1)
 - toolchain-xtensa-esp-elf @ 14.2.0+20241119
Reading CMake configuration...
-- git rev-parse returned 'fatal: not a git repository (or any of the parent directories): .git'
-- Minimal build - OFF
-- Building ESP-IDF components for target esp32s3
-- Configuring incomplete, errors occurred!

fatal: not a git repository (or any of the parent directories): .git
CMake Error at C:/Users/Melvin/.platformio/packages/framework-espidf/tools/cmake/build.cmake:629 (message):
  C:\Users\Melvin\.platformio\penv\.espidf-5.5.1\Scripts\python.exe: Error
  while finding module specification for
  'idf_component_manager.prepare_components' (ModuleNotFoundError: No module
  named 'idf_component_manager')

Call Stack (most recent call first):
  C:/Users/Melvin/.platformio/packages/framework-espidf/tools/cmake/project.cmake:740 (idf_build_process)
  CMakeLists.txt:3 (project)



==================================================================== [FAILED] Took 3.72 seconds ====================================================================
```

</details>

**Comment by ndrwrbgs** [comment]
@melgu can you make sure you try clean, it looks like this build used cached files

**Comment by melgu** [comment]
@ndrwrbgs I've removed the .esphome folder and executed the `esphome clean` command. Sadly, I still get the error.

<details>

<summary>Command Line Output</summary>

```
PS D:\Programme\ESPHome> esphome clean sensecap-indicator-1.yaml  
INFO ESPHome 2025.12.4
INFO Reading configuration sensecap-indicator-1.yaml...
INFO Deleting PlatformIO cache C:\Users\Melvin\.platformio\.cache
INFO Done!
PS D:\Programme\ESPHome> esphome compile sensecap-indicator-1.yaml
INFO ESPHome 2025.12.4
INFO Reading configuration sensecap-indicator-1.yaml...
INFO Generating C++ source...
INFO Core config or version changed, cleaning build files...
INFO Compiling app... Build path: D:\Programme\ESPHome\.esphome\build\sensecap-indicator-1
Processing sensecap-indicator-1 (board: esp32-s3-devkitc-1; framework: espidf; platform: https://github.com/pioarduino/platform-espressif32/releases/download/55.03.31-2/platform-espressif32.zip)
---------------------------------------------------------------------------------------------------------------------------------------
Library Manager: Installing esphome/noise-c @ 0.1.10
INFO Installing esphome/noise-c @ 0.1.10
Downloading  [####################################]  100%
Unpacking  [####################################]  100%
Library Manager: noise-c@0.1.10 has been installed!
INFO noise-c@0.1.10 has been installed!
Library Manager: Resolving dependencies...
INFO Resolving dependencies...
Library Manager: Installing esphome/libsodium @ 1.10020.7
INFO Installing esphome/libsodium @ 1.10020.7
Downloading  [####################################]  100%
Unpacking  [####################################]  100%
Library Manager: libsodium@1.10020.7 has been installed!
INFO libsodium@1.10020.7 has been installed!
Library Manager: Installing lvgl/lvgl @ 8.4.0
INFO Installing lvgl/lvgl @ 8.4.0
Downloading  [####################################]  100%
Unpacking  [####################################]  100%
Library Manager: lvgl@8.4.0 has been installed!
INFO lvgl@8.4.0 has been installed!
Verbose mode can be enabled via `-v, --verbose` option
CONFIGURATION: https://docs.platformio.org/page/boards/espressif32/esp32-s3-devkitc-1.html
PLATFORM: Espressif 32 (55.3.31) > Espressif ESP32-S3-DevKitC-1-N8 (8 MB QD, No PSRAM)
HARDWARE: ESP32S3 240MHz, 320KB RAM, 8MB Flash
DEBUG: Current (esp-builtin) On-board (esp-builtin) External (cmsis-dap, esp-bridge, esp-prog, iot-bus-jtag, jlink, minimodule, olimex-arm-usb-ocd, olimex-arm-usb-ocd-h, olimex-arm-usb-tiny-h, olimex-jtag-tiny, tumpa)
PACKAGES:
 - contrib-piohome @ 3.4.4
 - framework-espidf @ 3.50501.0 (5.5.1)
 - tool-cmake @ 4.0.3
 - tool-esp-rom-elfs @ 2024.10.11
 - tool-esptoolpy @ 5.1.0
 - tool-mklittlefs @ 3.2.0
 - tool-ninja @ 1.13.1
 - tool-scons @ 4.40801.0 (4.8.1)
 - toolchain-xtensa-esp-elf @ 14.2.0+20241119
Reading CMake configuration...
-- Found Git: C:/Program Files/Git/cmd/git.exe (found version "2.52.0.windows.1")
-- git rev-parse returned 'fatal: not a git repository (or any of the parent directories): .git'
-- Minimal build - OFF
-- The C compiler identification is GNU 14.2.0
-- The CXX compiler identification is GNU 14.2.0
-- The ASM compiler identification is GNU
-- Found assembler: C:/Users/Melvin/.platformio/packages/toolchain-xtensa-esp-elf/bin/xtensa-esp32s3-elf-gcc.exe
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: C:/Users/Melvin/.platformio/packages/toolchain-xtensa-esp-elf/bin/xtensa-esp32s3-elf-gcc.exe - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: C:/Users/Melvin/.platformio/packages/toolchain-xtensa-esp-elf/bin/xtensa-esp32s3-elf-g++.exe - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Building ESP-IDF components for target esp32s3
-- Configuring incomplete, errors occurred!

fatal: not a git repository (or any of the parent directories): .git
CMake Error at C:/Users/Melvin/.platformio/packages/framework-espidf/tools/cmake/build.cmake:629 (message):
  C:\Users\Melvin\.platformio\penv\.espidf-5.5.1\Scripts\python.exe: Error
  while finding module specification for
  'idf_component_manager.prepare_components' (ModuleNotFoundError: No module
  named 'idf_component_manager')

Call Stack (most recent call first):
  C:/Users/Melvin/.platformio/packages/framework-espidf/tools/cmake/project.cmake:740 (idf_build_process)
  CMakeLists.txt:3 (project)



===================================================== [FAILED] Took 24.43 seconds =====================================================
```


</details>

**Comment by ndrwrbgs** [comment]
🤔 

_P.s. It might be worth making a new issue; I’m worried about burying this thread and spamming folks 😆._

It sure looks like the same symptoms that the above “yaml” package caused, but I’m not versed enough on what clean commands EspHome UI in HomeAssistant was using.

What I can share that may help lead down the right paths is that I saw the .git error and debugged it first, but it was a a red herring (mislead) as it was a symptom of the earlier failure **leading to** the idf package not being built. Then on subsequent builds instead of getting the first failure, I _only_ got this “.git” failure, _unless_ I cleaned the build caches.

If you are running bare metal it may be worth going down the docker route so you get an entirely clean environment (high cost now but may save you issues later).

But I empathize that if you’re here, you’re currently focused on a different project and undertaking such a “fork” probably isn’t appealing. Some routes I’d try: Perhaps there’s another cache that is system wide and being hit? And there’s got to be some more verbose output available (cli flag?) since we aren’t seeing all of the minor steps in the build. Perhaps windows is doing its windows thing and not playing well with the Linux tooling - if that were the case I’d try to go down the routes discussed above of pinning the package version or forcing the import of the “clib” package, to avoid the build tools dependency.

_P.S. sent from mobile with a goal to not leave you blocked. Speed of sharing context prioritized over thoroughness. Desktop-quality research and spelling may be lacking._

**Comment by swoboda1337** [comment]
> [@ndrwrbgs](https://github.com/ndrwrbgs) I've removed the .esphome folder and executed the `esphome clean` command. Sadly, I still get the error.

Do a `clean-all` not `clean`.

The fix for 2025.12.4 was to install the python build essentials package in docker, it does nothing for windows. 

If you look at the failure it tells you how to fix it:
```
error: Microsoft Visual C++ 14.0 or greater is
required. Get it with "Microsoft C++ Build Tools":
https://visualstudio.microsoft.com/visual-cpp-build-tools/
```
