### ISSUE TITLE
ESPHome fails to complete startup with poor WiFi

### ISSUE THREAD

**Issue by dwmw2** [OttoWinter/esphomeyaml#9732]
### The problem

I have a blind controller running in a part of the house with very poor wireless coverage. Last updated with git HEAD about February, it was working OK. After an update (to git HEAD again) it just doesn't finish starting up and doesn't even respond to the local open/close buttons.

It repeats this, over and over:
```
[09:46:47][I][wifi:319]: Connecting to 'Lumleys'
[09:46:47][I][esp-idf:000][wifi]: W (158792) wifi:
[09:46:47][I][esp-idf:000][wifi]: Password length matches WPA2 standards, authmode threshold changes from OPEN to WPA2
[09:46:47][I][esp-idf:000][wifi]: 
[09:46:50][I][esp-idf:000][wifi]: I (161666) wifi:
[09:46:50][I][esp-idf:000][wifi]: new:<1,0>, old:<1,0>, ap:<255,255>, sta:<1,0>, prof:1, snd_ch_cfg:0x0
[09:46:50][I][esp-idf:000][wifi]: 
[09:46:50][I][esp-idf:000][wifi]: I (161668) wifi:
[09:46:50][I][esp-idf:000][wifi]: state: init -> auth (0xb0)
[09:46:50][I][esp-idf:000][wifi]: 
[09:46:50][W][component:417]: as5600.sensor took a long time for an operation (466 ms)
[09:46:50][W][component:418]: Components should block for at most 30 ms
[09:46:51][I][esp-idf:000][wifi]: I (162670) wifi:
[09:46:51][I][esp-idf:000][wifi]: state: auth -> init (0x200)
[09:46:51][I][esp-idf:000][wifi]: 
[09:46:51][I][esp-idf:000][wifi]: I (162672) wifi:
[09:46:51][I][esp-idf:000][wifi]: new:<1,0>, old:<1,0>, ap:<255,255>, sta:<1,0>, prof:1, snd_ch_cfg:0x0
[09:46:51][I][esp-idf:000][wifi]: 
[09:46:51][W][wifi_esp32:710]: Disconnected ssid='Lumleys' bssid=18:62:2C:5D:94:6C reason='Auth Expired'
[09:46:51][W][wifi:666]: Connecting to network failed
[09:46:51][I][wifi:319]: Connecting to 'Lumleys'

```

### Which version of ESPHome has the issue?

commit 5b3d61b4a6832

### What type of installation are you using?

pip

### What platform are you using?

ESP32

### Component causing the issue

wifi

### YAML Config

```yaml
https://git.infradead.org/?p=users/dwmw2/esp32-pool.git;a=blob;f=landing-blind-3.yaml
```

### Anything in the logs that might be useful for us?

```txt

```

**Comment by dwmw2** [comment]
It seems to be using the same BSSID every time even though there are three to choose from (of which it really ought to be able to see two). It never seems to scan. It's supposed to have the "known closest" BSSID as priority 1 and then fall back to scanning.

**Comment by dwmw2** [comment]
Having the second WiFi config with explicit BSSID doesn't make a difference here. If I remove that and just let it scan, it behaves just the same way.

I've temporarily switched `enable_on_boot` to false and re-enable it with a button press, although I need to experiment with when I can automatically enable it at boot. I'm away again this week but this should be fairly easy to reproduce by just configuring a non-existent SSID so it *never* connects (unless it does require seeing beacons and at least *trying*?).

When I get home I'll do that with a spare unit on my desk and try to bisect. I'm sure this was working correctly in February when I got https://github.com/esphome/esphome/pull/8325 working, but then was failing by the time that was finally merged this month.

**Comment by dwmw2** [comment]
Here's the full config, as requested on Discord.

[landing-blind-3.yaml.txt](https://github.com/user-attachments/files/21361693/landing-blind-3.yaml.txt)

```
wifi:
  networks:
    - ssid: \033[5m!secret 'wifi_ssid'\033[6m
      password: \033[5m!secret 'wifi_pw'\033[6m
      priority: 0.0
    - ssid: \033[5m!secret 'wifi_ssid'\033[6m
      password: \033[5m!secret 'wifi_pw'\033[6m
      bssid: \033[5m!secret 'wndr3800_bssid'\033[6m
      priority: 1.0
  enable_on_boot: false
  domain: .local
  reboot_timeout: 15min
  power_save_mode: LIGHT
  fast_connect: false
  enable_btm: false
  enable_rrm: false
  passive_scan: false
  use_address: landing-blind-3.local
```

Using `power_save_mode: none` doesn't help either; that's what it was set to.

**Comment by dwmw2** [comment]
I think this might be the same issue as https://github.com/esphome/esphome/issues/9786 

I will be able to test https://github.com/esphome/esphome/pull/9787 which allegedly fixes it, in a few days.

**Comment by dwmw2** [comment]
Or maybe it's fixed by https://github.com/esphome/esphome/pull/9823 ?

**Comment by bdraco** [comment]
This issue got auto closed because https://github.com/esphome/esphome/pull/9963 was merged and it was linked.  However that PR doesn't appear to solve this problem

**Comment by ssieb** [comment]
Is this still an issue?  If so, add serial logs.
